package services

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"tashi-backend/internal/config"
)

type ScriptService struct {
	config *config.Config
}

func NewScriptService(cfg *config.Config) *ScriptService {
	return &ScriptService{
		config: cfg,
	}
}

// SaveScript saves the generated script to a file and returns the file path
func (s *ScriptService) SaveScript(script, language, taskID string) (string, string, error) {
	// Determine file extension based on language
	ext := s.getFileExtension(language)

	// Generate filename with timestamp
	timestamp := time.Now().Format("20060102_150405")
	filename := fmt.Sprintf("tashi_script_%s_%s%s", taskID[:8], timestamp, ext)

	// Create full file path
	filePath := filepath.Join(s.config.OutputDir, filename)

	// Add shebang or header based on language
	finalScript := s.addScriptHeader(script, language)

	// Write script to file
	if err := os.WriteFile(filePath, []byte(finalScript), 0755); err != nil {
		return "", "", fmt.Errorf("failed to save script: %w", err)
	}

	return filePath, filename, nil
}

// getFileExtension returns the appropriate file extension for the language
func (s *ScriptService) getFileExtension(language string) string {
	switch strings.ToLower(language) {
	case "powershell":
		return ".ps1"
	case "bash", "shell":
		return ".sh"
	case "python":
		return ".py"
	case "batch":
		return ".bat"
	case "go", "golang":
		return ".go"
	default:
		return ".txt"
	}
}

// addScriptHeader adds appropriate headers/shebangs to scripts
func (s *ScriptService) addScriptHeader(script, language string) string {
	var header string

	switch strings.ToLower(language) {
	case "bash", "shell":
		if !strings.HasPrefix(script, "#!/") {
			header = "#!/bin/bash\n\n"
		}
	case "python":
		if !strings.HasPrefix(script, "#!/") {
			header = "#!/usr/bin/env python3\n\n"
		}
	case "powershell":
		header = "# PowerShell Script Generated by Tashi\n# Run with: powershell -ExecutionPolicy Bypass -File script.ps1\n\n"
	case "batch":
		header = "@echo off\nREM Batch Script Generated by Tashi\n\n"
	}

	// Add generation timestamp
	timestamp := time.Now().Format("2006-01-02 15:04:05")
	header += fmt.Sprintf("# Generated by Tashi on %s\n# Visit https://tashi.dev for more automation scripts\n\n", timestamp)

	return header + script
}

// ValidateScriptContent performs basic validation on script content
func (s *ScriptService) ValidateScriptContent(script, language string) []string {
	var warnings []string

	// Check for potentially dangerous commands
	dangerousPatterns := s.getDangerousPatterns(language)

	scriptLower := strings.ToLower(script)
	for pattern, warning := range dangerousPatterns {
		if strings.Contains(scriptLower, pattern) {
			warnings = append(warnings, warning)
		}
	}

	// Check script size
	if len(script) > int(s.config.MaxScriptSize) {
		warnings = append(warnings, "Script size exceeds maximum allowed size")
	}

	// Check for empty script
	if strings.TrimSpace(script) == "" {
		warnings = append(warnings, "Script content is empty")
	}

	return warnings
}

// getDangerousPatterns returns patterns that might indicate dangerous operations
func (s *ScriptService) getDangerousPatterns(language string) map[string]string {
	common := map[string]string{
		"rm -rf":            "WARNING: Recursive file deletion detected",
		"del /s":            "WARNING: Recursive file deletion detected",
		"format":            "WARNING: Disk formatting command detected",
		"shutdown":          "WARNING: System shutdown command detected",
		"reboot":            "WARNING: System reboot command detected",
		"registry":          "WARNING: Registry modification detected",
		"sudo":              "WARNING: Elevated privileges required",
		"curl":              "WARNING: Network request detected",
		"wget":              "WARNING: Network request detected",
		"invoke-webrequest": "WARNING: Network request detected",
	}

	switch strings.ToLower(language) {
	case "powershell":
		common["remove-item"] = "WARNING: File deletion command detected"
		common["invoke-expression"] = "WARNING: Dynamic code execution detected"
		common["start-process"] = "WARNING: Process execution detected"
		common["set-executionpolicy"] = "WARNING: Security policy modification detected"
	case "bash", "shell":
		common["chmod +x"] = "WARNING: File permission modification detected"
		common["> /dev/"] = "WARNING: System device access detected"
		common["dd if="] = "WARNING: Low-level disk operation detected"
	case "python":
		common["os.system"] = "WARNING: System command execution detected"
		common["subprocess"] = "WARNING: Process execution detected"
		common["exec("] = "WARNING: Dynamic code execution detected"
		common["eval("] = "WARNING: Dynamic code evaluation detected"
	}

	return common
}

// GetScriptPreview generates a preview of the script with syntax highlighting hints
func (s *ScriptService) GetScriptPreview(script, language string) map[string]interface{} {
	lines := strings.Split(script, "\n")

	preview := map[string]interface{}{
		"language":   language,
		"line_count": len(lines),
		"char_count": len(script),
		"preview":    s.truncateScript(script, 500), // First 500 chars
		"structure":  s.analyzeScriptStructure(script, language),
	}

	return preview
}

// truncateScript truncates script content for preview
func (s *ScriptService) truncateScript(script string, maxChars int) string {
	if len(script) <= maxChars {
		return script
	}

	truncated := script[:maxChars]
	lastNewline := strings.LastIndex(truncated, "\n")
	if lastNewline > 0 {
		truncated = truncated[:lastNewline]
	}

	return truncated + "\n... (truncated)"
}

// analyzeScriptStructure provides basic structure analysis
func (s *ScriptService) analyzeScriptStructure(script, language string) map[string]interface{} {
	lines := strings.Split(script, "\n")
	structure := map[string]interface{}{
		"functions": 0,
		"variables": 0,
		"comments":  0,
		"imports":   0,
	}

	for _, line := range lines {
		line = strings.TrimSpace(line)

		switch strings.ToLower(language) {
		case "python":
			if strings.HasPrefix(line, "def ") {
				structure["functions"] = structure["functions"].(int) + 1
			}
			if strings.HasPrefix(line, "import ") || strings.HasPrefix(line, "from ") {
				structure["imports"] = structure["imports"].(int) + 1
			}
			if strings.HasPrefix(line, "#") {
				structure["comments"] = structure["comments"].(int) + 1
			}
			if strings.Contains(line, " = ") {
				structure["variables"] = structure["variables"].(int) + 1
			}
		case "bash", "shell":
			if strings.HasPrefix(line, "function ") || strings.Contains(line, "() {") {
				structure["functions"] = structure["functions"].(int) + 1
			}
			if strings.HasPrefix(line, "#") {
				structure["comments"] = structure["comments"].(int) + 1
			}
			if strings.Contains(line, "=") && !strings.Contains(line, "==") {
				structure["variables"] = structure["variables"].(int) + 1
			}
		case "powershell":
			if strings.HasPrefix(line, "function ") || strings.HasPrefix(line, "Function ") {
				structure["functions"] = structure["functions"].(int) + 1
			}
			if strings.HasPrefix(line, "#") {
				structure["comments"] = structure["comments"].(int) + 1
			}
			if strings.HasPrefix(line, "$") {
				structure["variables"] = structure["variables"].(int) + 1
			}
		}
	}

	return structure
}

// CleanupOldFiles removes old generated files to save disk space
func (s *ScriptService) CleanupOldFiles(maxAge time.Duration) error {
	return filepath.Walk(s.config.OutputDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if !info.IsDir() && time.Since(info.ModTime()) > maxAge {
			if err := os.Remove(path); err != nil {
				return fmt.Errorf("failed to remove old file %s: %w", path, err)
			}
		}

		return nil
	})
}
